// src/engine/audit_export.rs — Cryptographic Security & Container Audit Report Exporter
// Generates structured Markdown reports detailing container analysis, cipher strength, and KDF postures.

use std::fs;
use std::path::{Path, PathBuf};
use chrono::Utc;
use crate::app::{FileAnalysis, Session};

pub fn export_audit_report(
    analysis: &FileAnalysis,
    sessions: &[Session],
    current_dir: &Path,
) -> Result<PathBuf, String> {
    let target_filename = Path::new(&analysis.file_path)
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "audit".into());

    let clean_name = target_filename.replace(['/', '\\', ' ', ':'], "_");
    let report_filename = format!("torcrypt_audit_{}.md", clean_name);
    let output_path = current_dir.join(&report_filename);

    let now_str = Utc::now().format("%Y-%m-%d %H:%M:%S UTC").to_string();

    // Security rating heuristic
    let (security_rating, posture_note) = if !analysis.is_encrypted {
        ("UNENCRYPTED", "File is in plaintext. No confidentiality protection is present.")
    } else if analysis.lock_type.contains("ZipCrypto") || analysis.lock_type.contains("RC4") || analysis.lock_type.contains("MD5") {
        ("INSECURE / LEGACY", "Vulnerable to key reduction, stream cipher collisions, or instant plaintext recovery.")
    } else if analysis.lock_type.contains("Argon2") || analysis.lock_type.contains("AES-256") || analysis.lock_type.contains("ChaCha20") {
        ("ROBUST / PRODUCTION", "Uses modern, high-work-factor cryptographic primitives compliant with FIPS/RFC standards.")
    } else {
        ("MODERATE", "Standard symmetric protection; ensure strong passphrase entropy is enforced.")
    };

    let mut md = String::new();
    md.push_str("# 🔐 TORCRYPT Cryptographic Security & Container Inspection Audit\n\n");
    md.push_str(&format!("*Generated by Torcrypt Engine on {}*\n\n", now_str));
    md.push_str("---\n\n");

    // 1. Target Metadata
    md.push_str("## 📋 Target Container Overview\n\n");
    md.push_str("| Attribute | Value |\n");
    md.push_str("|---|---|\n");
    md.push_str(&format!("| **Target Path** | `{}` |\n", analysis.file_path));
    md.push_str(&format!("| **File Size** | {} bytes ({:.2} MB) |\n", analysis.file_size, analysis.file_size as f64 / 1_048_576.0));
    md.push_str(&format!("| **Container Format** | `{}` |\n", analysis.mime_type));
    md.push_str(&format!("| **Shannon Entropy** | `{:.4} / 8.0000` bits/byte |\n", analysis.entropy));
    md.push_str(&format!("| **Magic Header** | `{}` |\n", analysis.magic_header));
    md.push_str(&format!("| **Encryption Status** | `{}` |\n\n", if analysis.is_encrypted { "🔒 ENCRYPTED" } else { "🔓 PLAINTEXT" }));

    // 2. Cryptographic Profile
    md.push_str("## 🛡️ Identified Cryptographic Profile\n\n");
    md.push_str(&format!("* **Detected Lock / Cipher Suite:** {}\n", analysis.lock_type));
    md.push_str(&format!("* **Recommended Pipeline:** {}\n", analysis.recommended_engine.display_name()));
    md.push_str(&format!("* **Recovery Strategy Recommendation:** {}\n\n", analysis.recommended_attack));

    // 3. Security Evaluation
    md.push_str("## ⚠️ Cryptographic Posture Assessment\n\n");
    md.push_str(&format!("* **Security Posture Rating:** **`{}`**\n", security_rating));
    md.push_str(&format!("* **Analysis Finding:** {}\n\n", posture_note));

    // 4. Session History
    if !sessions.is_empty() {
        md.push_str("## 📊 Recent Session Registry Summary\n\n");
        md.push_str("| Session ID | Target | Cipher | Status | Date |\n");
        md.push_str("|---|---|---|---|---|\n");
        for s in sessions.iter().take(5) {
            md.push_str(&format!("| `{}` | `{}` | `{}` | `{}` | `{}` |\n", s.id, s.target, s.cipher, s.status, s.created_at));
        }
        md.push('\n');
    }

    md.push_str("---\n");
    md.push_str("*Torcrypt — High-Performance Cryptographic Analysis & Decryption Suite*\n");

    fs::write(&output_path, md).map_err(|e| format!("Failed to write report: {}", e))?;
    Ok(output_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::app::ComputeEngine;

    #[test]
    fn test_export_audit_report() {
        let analysis = FileAnalysis {
            file_path: "/tmp/test_vault.zip".into(),
            file_size: 1048576,
            mime_type: "application/zip".into(),
            is_encrypted: true,
            lock_type: "WinZip AES-256".into(),
            entropy: 7.92,
            magic_header: "PK 03 04".into(),
            recommended_attack: "Leveled Wordlist".into(),
            recommended_engine: ComputeEngine::CpuSimd,
            ready_to_crack: true,  // ZIP with known verifier: acceptable in test
        };

        let temp_dir = std::env::temp_dir();
        let path = export_audit_report(&analysis, &[], &temp_dir).expect("Export should succeed");

        assert!(path.exists());
        let content = fs::read_to_string(&path).expect("Read report");
        assert!(content.contains("TORCRYPT Cryptographic Security"));
        assert!(content.contains("WinZip AES-256"));
        assert!(content.contains("ROBUST / PRODUCTION"));

        let _ = fs::remove_file(path);
    }
}
